; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[project_options]
;program_name = UART8w
;program_name = UART8r 
;program_name = EEPROM
;program_name = main_linesensor
;program_name = sub_linesensor
;program_name = main
;program_name = sub
;program_name = ball_main
;program_name = ball_sub
;program_name = Gyromain
;program_name = Gyrosub
;program_name = noline_main
;program_name = noline_sub
;program_name = KICKER
;program_name = finalmain
;program_name = finalsub
;program_name = test
;program_name = testsub
;program_name = testsubattack
;program_name = ball_front_control
;program_name = BLDC
;program_name = NJL70L
;program_name = US
;program_name = ball_main_comm
;program_name = ball_main_vector_field
;program_name = ball_sub_line
;program_name = US_ball_main_comm
;program_name = position_kalman_test
;program_name = main_ball
;program_name = sub_ball
;program_name = subtest
program_name = maintest
[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_src_filter = +<*.h> +<${project_options.program_name}.cpp>
